name: Lint and test with poetry
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
	default: '3.10'
      poetry-version:
        required: false
        type: string
        default: '1.3.1'
      sources-folder:
        required: false
	type: string
	default: 'src'
      unittest-folder:
        required: false
        type: string
	default: 'tests'
      unittest-flags:
        required: false
        type: string
	default: 'unittest'
      integration-folder:
        required: false
	type: string
	default: ''
      integration-flags:
        required: false
        type: string
	default: ''
      base-folder:
        required: false
	type: string
	default: '.'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ inputs.poetry-version }}
      - name: Install dependencies
        run: |
          cd ${{ inputs.base-folder }}
          poetry install --no-root
      - name: Black styling
        run: |
          cd ${{ inputs.base-folder }}
          poetry run black --verbose --check ${{ inputs.sources-folder }}
      - name: Unittests with pytest
        run: |
          cd ${{ inputs.base-folder }}
          poetry run pytest -x ${{ inputs.unittest-folder }} --cov ${{ inputs.sources-folder }} --cov-report xml
      - name: Upload unittest coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{ inputs.base-folder }}/coverage.xml
          flags: ${{ inputs.unittest-flags }}
      - name: Integration tests with pytest
        if: ${{ inputs.integration-folder }} != ''
        run: |
          cd ${{ inputs.base-folder }}
          poetry run pytest -x ${{ inputs.integration-folder }} --cov ${{ inputs.sources-folder }} --cov-report xml
      - name: Upload integration coverage to Codecov
        if: ${{ inputs.integration-flags }} != ''
        uses: codecov/codecov-action@v3
        with:
          files: ${{ inputs.base-folder }}/coverage.xml
          flags: ${{ inputs.integration-flags }}
